fileVersion: 1
id: c08b85eb-9873-49c4-912d-aa249b3a151b
name: ROUTES
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: SOURCE
  metadata:
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 8bc461e2-14a8-40ab-bf39-421ef9498e07
          stepCounter: c08b85eb-9873-49c4-912d-aa249b3a151b
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: SOURCE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: fcab15a7-8142-4896-86fa-3c107a10bbf5
          stepCounter: c08b85eb-9873-49c4-912d-aa249b3a151b
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: DESTINATION
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
  name: ROUTES
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
